### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jframeau** [naemon/naemon-livestatus#112]
On debian 11.4, omd 5.10.

naemon segfaults with the following stacktrace (read from core dump):

#0  0x00007f28205f48a7 in Logfile::freeMessages(unsigned int) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#1  0x00007f28205f408a in LogCache::handleNewMessage(Logfile*, long, long, unsigned int) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#2  0x00007f28205f4c27 in Logfile::loadRange(_IO_FILE*, unsigned int, LogCache*, long, long, unsigned int) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#3  0x00007f28205f4e3d in Logfile::load(LogCache*, long, long, unsigned int) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#4  0x00007f28205f4fb7 in Logfile::answerQueryReverse(Query*, LogCache*, long, long, unsigned int) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#5  0x00007f28205fb0f5 in TableLog::answerQuery(Query*) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#6  0x00007f28205cfec0 in Store::answerGetRequest(InputBuffer*, OutputBuffer*, char const*) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#7  0x00007f28205d015a in Store::answerRequest(InputBuffer*, OutputBuffer*) () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#8  0x00007f28205cf2b9 in store_answer_request () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#9  0x00007f2820600de5 in client_thread () from /omd/sites/xpertvision/lib/naemon/livestatus.o
#10 0x00007f2821756ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f28218e2a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Segfault is highly random.

jfr

**Comment by sni** [comment]
could you check if this still happens with OMD 5.20?
