### ISSUE TITLE
[Feature] Export as status.dat or retention.dat format

### ISSUE THREAD

**Issue by juaningan** [naemon/naemon-livestatus#17]
Hi, I'm working in a distributed naemon core using merlin, works well but prior to run a new naemon peer I have to sync status.dat -> retention.dat from a webserver where previously I have get a status.dat file from cluster via webserver. Homemade solution but also working well.

My request is to query all the status info from livestatus and format it in a retention.dat/status.dat compatible syntax. Do you think it is possible?

Thanks in advance.

**Comment by sni** [comment]
You should be able to get all information by livestatus which are required to write a status.dat by a script. But you have to write that script yourself.
