### ISSUE TITLE
Timeperiod Transition in naemon logfile for SLA Reporting

### ISSUE THREAD

**Issue by lindi2405** [naemon/naemon-livestatus#18]
We are using naemon-1.0.6 and SLA Reporting by Thruk. Since the upgrade from naemon-1.0.3 to naemon-1.0.6 we considered that no timeperiod transitions were logged in naemon logfile.
Before the upgrade we had entries like this

[1293066460] TIMEPERIOD TRANSITION: workhours;1;0

and after restart of naemon like this

[1293030953] TIMEPERIOD TRANSITION: 24x7;-1;1
[1293030953] TIMEPERIOD TRANSITION: none;-1;0
[1293030953] TIMEPERIOD TRANSITION: workhours;-1;1

In Version naemon-1.0.6 Only transitions are written into the logfile after the restart of naemon.
Now SLA Reporting is'nt working correctly because timeperiods are not considered.

Are the any changes in the new Version or what can i do to correct my SLA Reporting ?

Thank you for your help.

best regards

**Comment by sni** [comment]
should be fixed by 15fb30d4d46 meanwhile which is included in the 1.0.8 release.
