### ISSUE TITLE
Syntax error during ./configure

### ISSUE THREAD

**Issue by LikoV2** [naemon/naemon-livestatus#25]
Hi,

On CentOS 6.9, I type ./configure CPPFLAGS=-I$

It fails at:

checking for ICU... ./configure: line 15954: syntax error near unexpected token `4.2,'
./configure: line 15954: `                AX_CHECK_ICU(4.2, have_icu=yes, have_icu=no)'

I tried to install libicu:

Package libicu-4.2.1-14.el6.x86_64 already installed and latest version

**Comment by fmikker** [comment]
Hi,
You probably need the development package: libicu-devel

**Comment by AnthonyXtraball** [comment]
Hi,

Thanks for your response. Libiciu-devel was not installed, but it didn't solve the issue.

**Comment by fmikker** [comment]
@LikoV2 What distribution are you trying to build the source on?

Do you have the dependent development packages installed, such as naemon-devel?
You can find the packages for your distribution here: http://www.naemon.org/download/
