### ISSUE TITLE
livestatus.so segfault

### ISSUE THREAD

**Issue by deorth** [naemon/naemon-livestatus#9]
We're running naemon 1.0.0-1 (I know, not quite the latest)

It's been running fine for a couple of weeks with no issues, then this morning, we got a restart. Investigations show a segfault with livestatus.so.

Apr  6 13:02:02 myhost kernel: [567203.918161] naemon[59627]: segfault at 20 ip 00007f8259609c50 sp 00007f825a967e08 error 4 in livestatus.so[7f82595e7000+6d000]

Performance stats show that we make approx 360 NEB callbacks/second. 453k callbacks since the restart approx 4 hours ago.

The installed rpm is a build from 2/13 :

[ahorn@myhost]$ rpm -qi naemon-livestatus
Name        : naemon-livestatus            Relocations: (not relocatable)
Version     : 1.0.0                             Vendor: Naemon Core Development Team
Release     : 1.el6                         Build Date: Fri 13 Feb 2015 07:06:18 PM UTC
Install Date: Mon 30 Mar 2015 11:23:08 PM UTC      Build Host: mon-build-centos6-0-64.virt.consol.de
Group       : Applications/System           Source RPM: naemon-1.0.0-1.el6.src.rpm
Size        : 470136                           License: GPLv2
Signature   : (none)
Packager    : Naemon Core Development Team <naemon-dev@monitoring-lists.org>
URL         : http://www.naemon.org/
Summary     : Naemon Livestatus Eventbroker Module
Description :
contains the naemon livestatus eventbroker module.

I'm happy to gather any other information that may help, let me know.

**Comment by catharsis** [comment]
Sorry to get back to you so late. We've been fixing a slew of different segfault bugs since this was reported. I'm going to close this, but if you experience it again on a later release (one released after the merging #11, preferrably)
