### ISSUE TITLE
Livestatus shows a user twice on the contacts field

### ISSUE THREAD

**Issue by lamaral** [naemon/naemon-livestatus#90]
This issue arises when you have a user assigned to two different contact groups and these contact groups assigned to the same host. 
Livestatus will list the user twice on the contacts column and we ended up with problems when  running logcache updates on Thruk side. 

**Naemon Version**
naemon-core 1.2.4
naemon-livestatus 1.2.4.1
On Debian Buster

**To Reproduce**
1. Have two different contact groups that contain the same user assigned to the same host.
2. Query livestatus for the host and verify that the contacts column contains the given username twice.

**Expected behavior**
The username shows up only once in the contacts column. 

**Additional context**
I can't really precise when this became an issue, because unfortunately, the failure on Thruk side when running authupdate went under our radar for a while. 

Feel free to ask for more details if needed. 

Thank you

**Comment by sni** [comment]
thanks, found the issue. Should be fine with the above patch.
