### ISSUE TITLE
unsorted contacts host/service column

### ISSUE THREAD

**Issue by mittma** [naemon/naemon-livestatus#95]
With the current release of OMD 4.40 (naemon 1.0.3) the contacts column in host and service overview is unsorted. This did work with the previous version (OMD 4.30 and naemon 1.0.2) - do we need a final sorting after the duplicate detection (#91)?

best regards,
Martin.

**Comment by sni** [comment]
I cannot reproduce this. Contacts should be sorted, no matter what order they are configured. Making them unique does not change the order.
Could you by chance try the latest OMD nightly. Although nothing has changed to my knowledge in that direction.
Are you querying naemon livestatus directly?
