### ISSUE TITLE
rpm build error: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly

### ISSUE THREAD

**Issue by olahaye74** [naemon/naemon-livestatus#99]
Since Fedora-33, RHEL-8, %__python is not valid anymore and produce an error it you try to use it.
Please update rpm spec file to avoid %__python use. Instead use %__python3 on recent distress and %__python2 on old ones (reel-6 and reel-7)

Error message:
error: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
error: line 54: install -d %buildroot%{python_sitelib}/livestatus

how to reproduce (on AlmaLinux-8 for example):
rpm build -tb naemon-livestatus-1.3.1.tar.gz

**Comment by sni** [comment]
Is this still an issue, the builds on OBS look fine: https://build.opensuse.org/package/show/home:naemon/naemon-livestatus (including latest fedora and alma)
